runtime: nodejs20
instance_class: F2

env_variables:
  NODE_ENV: production

handlers:
  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
  - url: /
    static_dir: dist
    secure: always
